


spring.config.import=optional:classpath:application-secret.properties

spring.application.name=demo

# MongoDB 연결 주소 (환경변수로 숨김)
spring.data.mongodb.uri=${MONGO_URI}

# 외부 API 키 관리 (환경변수로 숨김)
api.key.public-data=${PUBLIC_DATA_KEY}
api.key.bizno=${BIZNO_KEY}
api.key.dart=${DART_KEY}