spring.application.name=demo

# MongoDB 연결 설정 (아래 주소는 본인의 몽고디비 URI로 변경하세요!)
spring.data.mongodb.uri="mongodb+srv://emptyboy85:Pa%24%24w0rd85@cluster0.sxfxuqp.mongodb.net/ticketing?retryWrites=true&w=majority&appName=Cluster0"
